### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by DexterSK** [BananaPuncher714/NBTEditor#31]
```
[12:47:49 WARN]: java.lang.reflect.InvocationTargetException
[12:47:49 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:47:49 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[12:47:49 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:47:49 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[12:47:49 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[12:47:49 WARN]:        at utils.NBTEditor.getHead(NBTEditor.java:461)
```

**Comment by BananaPuncher714** [comment]
Thanks, I'll try to update NBTEditor this weekend.

**Comment by DexterSK** [comment]
Thanks you too! :)

**Comment by BananaPuncher714** [comment]
Thanks, it seems that the 1.20.2 constructor for a GameProfile has a null check for the name, which wasn't there previously.
