### ISSUE TITLE
Spigot 1.20.1 setTag method not work

### ISSUE THREAD

**Issue by YXMAX** [BananaPuncher714/NBTEditor#39]
Code:
`litem = NBTEditor.set(litem, player.getName(), NBTEditor.CUSTOM_DATA, "playerinv:large");`

Error:
```
[21:13:21] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.a(net.minecraft.core.HolderLookup$a)
[21:13:21] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[21:13:21] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor$ReflectionTarget.fetchMethod(NBTEditor.java:1798)
[21:13:21] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.getMethod(NBTEditor.java:231)
[21:13:21] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.setItemTag(NBTEditor.java:536)
[21:13:21] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1222)
[21:13:21] [Server thread/WARN]: 	at com.playerinv.PermItem.PermItem.largeitem_owner(PermItem.java:48)
[21:13:21] [Server thread/WARN]: 	at com.playerinv.PermItem.PermItem.linvitem(PermItem.java:21)
[21:13:21] [Server thread/WARN]: 	at com.playerinv.Command.InvCommand.onCommand(InvCommand.java:848)
[21:13:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:13:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[21:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877)
[21:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[21:13:21] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[21:13:21] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018)
[21:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[21:13:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
[21:13:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'inv' in plugin PlayerInv v4.7.14
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because the return value of "io.github.bananapuncher714.nbteditor.NBTEditor.getMethod(io.github.bananapuncher714.nbteditor.NBTEditor$MethodId)" is null
	at io.github.bananapuncher714.nbteditor.NBTEditor.setItemTag(NBTEditor.java:536) ~[?:?]
	at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1222) ~[?:?]
	at com.playerinv.PermItem.PermItem.largeitem_owner(PermItem.java:48) ~[?:?]
	at com.playerinv.PermItem.PermItem.linvitem(PermItem.java:21) ~[?:?]
	at com.playerinv.Command.InvCommand.onCommand(InvCommand.java:848) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by BananaPuncher714** [comment]
Can you try clearing your maven cache, making sure you're using version 7.19.7 and rebuild? There has been some minor updates to the same version that should have fixed any previous issues.

**Comment by YXMAX** [comment]
I try the v7.19.7 and only keep a version v7.19.7 on maven, and it's the same.

```
[12:36:54] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.a(net.minecraft.core.HolderLookup$a)
[12:36:54] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor$ReflectionTarget.fetchMethod(NBTEditor.java:1861)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.getMethod(NBTEditor.java:232)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.setItemTag(NBTEditor.java:557)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1275)
[12:36:54] [Server thread/WARN]: 	at com.playerinv.PermItem.PermItem.largeitem_owner(PermItem.java:48)
[12:36:54] [Server thread/WARN]: 	at com.playerinv.PermItem.PermItem.linvitem(PermItem.java:21)
[12:36:54] [Server thread/WARN]: 	at com.playerinv.Command.InvCommand.onCommand(InvCommand.java:848)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[12:36:54] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[12:36:54] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[12:36:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
[12:36:54] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.a(net.minecraft.core.HolderLookup$a,net.minecraft.nbt.NBTTagCompound)
[12:36:54] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor$ReflectionTarget.fetchMethod(NBTEditor.java:1861)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.getMethod(NBTEditor.java:232)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.createItemStack(NBTEditor.java:311)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.setItemTag(NBTEditor.java:583)
[12:36:54] [Server thread/WARN]: 	at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1275)
[12:36:54] [Server thread/WARN]: 	at com.playerinv.PermItem.PermItem.largeitem_owner(PermItem.java:48)
[12:36:54] [Server thread/WARN]: 	at com.playerinv.PermItem.PermItem.linvitem(PermItem.java:21)
[12:36:54] [Server thread/WARN]: 	at com.playerinv.Command.InvCommand.onCommand(InvCommand.java:848)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877)
[12:36:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[12:36:54] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[12:36:54] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018)
[12:36:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[12:36:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
[12:36:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'inv' in plugin PlayerInv v4.7.14
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:877) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1924) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at net.minecraft.world.entity.item.EntityItem.a(EntityItem.java:488) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:73) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:66) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItem(CraftWorld.java:495) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItemNaturally(CraftWorld.java:519) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItemNaturally(CraftWorld.java:507) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at com.playerinv.PermItem.PermItem.linvitem(PermItem.java:21) ~[?:?]
	at com.playerinv.Command.InvCommand.onCommand(InvCommand.java:848) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

Code:
```
    public static void linvitem(Player player,int amount){
        player.getWorld().dropItemNaturally(player.getLocation(),largeitem_owner(player,amount));
    }


    public static ItemStack largeitem_owner(Player player,int amount){
        ItemStack litem = new ItemStack(Material.getMaterial(voucher_owner_large_material()),amount);
        ItemMeta lim = litem.getItemMeta();
        if(voucher_owner_large_enchant_glow()){
            lim.addEnchant(Enchantment.MENDING, 1, false);
            lim.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        }
        if(plugin.getConfig().contains("Voucher.large.custom-model-data")){
            if(!is113 && !isBelow113){
                lim.setCustomModelData(voucher_owner_large_custom_data());
            }
        }
        lim.setDisplayName(color(Locale_Voucher_Large_DisplayName()));
        ArrayList<String> lorelist = new ArrayList<String>();
        List<String> list = Locale_Voucher_Large_Lore();
        for(String s : list){
            lorelist.add(color(s.replaceAll("%voucher_player%", player.getName())));
        }
        lim.setLore(lorelist);
        litem.setItemMeta(lim);
        litem = NBTEditor.set(litem, player.getName(), NBTEditor.CUSTOM_DATA, "playerinv:large");
        return litem;
    }
```

**Comment by BananaPuncher714** [comment]
Ok thanks, I'll take a look at this

**Comment by BananaPuncher714** [comment]
This should be fixed as of the latest commit. It is still version `7.19.7`, so please try clearing your maven cache and recompiling.
